# Generated by Django 4.0 on 2024-03-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
