# Generated by Django 4.0 on 2024-03-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_datapoint_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='end_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
