# Generated by Django 4.0 on 2024-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_datapoint_added_alter_datapoint_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
